import SubjectAdd/validSubjectCode
import SubjectAdd/validName
import SubjectAdd/validSubjectType
import SubjectAdd/validP1Len
import SubjectAdd/validP2Len
import SubjectAdd/validPracLen
import SubjectAdd/validCDate